using EPiServer.Core;
using EPiServer.ServiceLocation;
using EPiServer.SocialAlloy.Web.Social.Blocks;
using EPiServer.SocialAlloy.Web.Social.Common.Controllers;
using EPiServer.SocialAlloy.Web.Social.Common.Exceptions;
using EPiServer.SocialAlloy.Web.Social.Models;
using EPiServer.SocialAlloy.Web.Social.Repositories;
using System;
using System.Web.Mvc;

namespace EPiServer.SocialAlloy.Web.Social.Controllers
{
    /// <summary>
    /// The FeedBlockController handles the rendering of feed items, if any, that were automatically
    /// generated by the Social Activity Streams system in response to activities occuring on any 
    /// target items that the logged in user has subscribed to.
    /// </summary>
    public class FeedBlockController : SocialBlockController<FeedBlock>
    {
        private readonly IUserRepository userRepository;
        private readonly ISocialFeedRepository feedRepository;
        private const string errorGettingUserIdMessage = "There was an error identifying the logged in user.Please make sure you are logged in and try again.";

        /// <summary>
        /// Constructor
        /// </summary>
        public FeedBlockController()
        {
            this.userRepository = ServiceLocator.Current.GetInstance<IUserRepository>();
            this.feedRepository = ServiceLocator.Current.GetInstance<ISocialFeedRepository>();
        }

        /// <summary>
        /// Render the feed block frontend view.
        /// </summary>
        /// <param name="currentBlock">The current frontend block instance.</param>
        /// <returns>The action's result.</returns>
        public override ActionResult Index(FeedBlock currentBlock)
        {
            var currentBlockLink = ((IContent)currentBlock).ContentLink;

            // Create a feed block view model to fill the frontend block view
            var blockViewModel = new FeedBlockViewModel(currentBlock);

            // If user logged in, retrieve activity feed for logged in user
            if (this.User.Identity.IsAuthenticated)
            {
                GetSocialActivityFeed(currentBlock, blockViewModel);
            }

            return PartialView("~/Views/Social/FeedBlock/FeedView.cshtml", blockViewModel);
        }

        /// <summary>
        /// Gets the activity feed for the logged in user
        /// </summary>
        /// <param name="currentBlock">The current frontend block instance.</param>
        /// <param name="blockViewModel">a reference to the FeedBlockViewModel to 
        ///populate with activity feed for the logged in user and errors, if any</param>
        private void GetSocialActivityFeed(FeedBlock currentBlock, FeedBlockViewModel blockViewModel)
        {
            blockViewModel.DisplayErrorMessage = String.Empty;

            try
            {
                var userId = userRepository.GetUserId(this.User);
                if (!String.IsNullOrWhiteSpace(userId))
                {
                    blockViewModel.FeedItems =
                        this.feedRepository.Get(new SocialFeedFilter
                        {
                            Subscriber = userId,
                            PageSize = currentBlock.FeedDisplayMax
                        });
                }
                else
                {
                    blockViewModel.DisplayErrorMessage = errorGettingUserIdMessage;
                }
            }
            catch (SocialRepositoryException ex)
            {
                blockViewModel.DisplayErrorMessage = ex.Message;
            }
        }
    }
}